# Generated by Django 2.2 on 2022-05-31 00:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusSenha',
            fields=[
                ('id_status_senha', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id_senha', models.AutoField(primary_key=True, serialize=False)),
                ('senha', models.IntegerField()),
                ('hora_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel_senhas.Categoria')),
                ('fk_status_senha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel_senhas.StatusSenha')),
                ('fk_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel_senhas.Tipo')),
            ],
        ),
    ]
